# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: walrus_development
test:
  <<: *default
  database: walrus_test
production:
  <<: *default
  database: walrus_production
  username: walrus
  password: <%= ENV['walrus_DATABASE_PASSWORD'] %>
